### ISSUE TITLE
PackageJson - Refactor into a simple module

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/tooling-helpers#24]
A JavaScript class is giving us nothing here: refactor the class that this tooling helper provides as a simple module. Also, add tests!

Related issue https://github.com/Financial-Times/next/issues/297.

#### TODOs

- [x] Re-implement `loadPackageJson`
- [x] Re-implement `getField`
- [x] Re-implement `setField`
- [x] Re-implement `requireDependency`
- [x] Re-implement `removeDependency`
- [x] Re-implement `requireScript`
- [x] Re-implement `hasChangesToWrite`
- [x] Re-implement `write` -> `writeChanges`
- [x] Re-implement and move helpers: `deepCloneObject` and `formatObjectAsJson` - SP
- [x] Remove `writeImmediately` functionality - JS
- [x] Write tests for `getField`
- [x] Write tests for `setField`
- [x] Write tests for `requireDependency`
- [x] Write tests for `removeDependency`
- [x] Write tests for `requireScript`
- [x] Write tests for helpers: `deepCloneObject` and `formatObjectAsJson`
- [x] Write tests for `hasChangesToWrite`
- [x] Write tests for `loadPackageJson`
- [x] Refactor the changelog into its own module and write tests i.e. all the `getChangelog*` methods
- [x] Write tests for `writeChanges`
- [x] Expose `packageJson.changelog` - avoid exposing `changelog.createEntry()` method
- [x] Implement the final few tests (the ones that are being skipped)
- [x] Add `.editorconfig` etc. and reformat all files with Prettier
- [x] Fix tests that are failing on CI - https://circleci.com/gh/Financial-Times/tooling-helpers/148
- [x] Code review changes
- [x] Add missing `alreadyExisted` property to `setField` changelog entry
- [x] Manual testing with existing transformations - https://github.com/Financial-Times/next-transformations/compare/temp-package-json-v2-compatibility
- [x] Rename `getDocument` to `get`
- [x] Update `README`

**Comment by simonplend** [comment]
Copy TODOs from https://github.com/Financial-Times/tooling-helpers/pull/64
