### ISSUE TITLE
Change node versions

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/tooling-helpers#60]
#### What and why

- `package.json#engines.node` fields should reflect all the versions of node that the package can be used under ([example](https://github.com/Financial-Times/github/blob/30a0cff15f0af3c55dcbe71720685a42a91c2907/package.json#L37)).

- CircleCi should run the tests for this repository under each version of node that the packages support ([example](https://github.com/Financial-Times/github/blob/d0fc553903e7c7d2e6e796e35f8b5e015eabc672/.circleci/config.yml)).

- This repository's `.nvmrc` file should reflect the oldest version of node that we support so that we don't develop code that can't be run  i.e. `8` ([example](https://github.com/Financial-Times/github/blob/89cbbd44dcbcf39395538133d3a80679dfb7fda2/.nvmrc))

#### TODOs

- [ ] Update `package.json#engines.node` field for the `git` package
- [ ] Update `package.json#engines.node` field for the `package-json` package
- [ ] Update CircleCI configuration (`.circleci/config.yml`)
- [ ] Update the project's `.nvmrc` file

**Comment by simonplend** [comment]
See https://github.com/Financial-Times/tooling-helpers/pull/56#issuecomment-468637603

**Comment by adambraimbridge** [comment]
But 10.x.x is LTS, and will be relevant long after v8.x.x is deprecated. Right?

**Comment by simonplend** [comment]
Correct. However, this monorepo contains packages, not apps, so we actually want `engines.node` in `package.json` to reflect what versions of node they can be used under. In which case, now I think about it, it would probably make sense for things to diverge slightly...

- `package.json#engines.node` - reflect the versions of node that the libraries can be used under e.g. `>8.0.0`
- `.circleci/config.yml` - we should probably be running our tests under multiple versions of node as part of every build
- `.nvmrc` - reflect the oldest version of node that we support so that we don't develop code that can't be run  e.g. `8.0.0`

The `package.json` and `.nvmrc` settings should be per package, whereas the CircleCI config will be at a repository level. This will all be much simpler when the remaining two packages are in their own repositories. Kind of wishing I'd done that instead of converting this into a monorepo, but eh, that's the benefit of hindsight for you.

I'll write up a checklist of actions so this all makes a bit more sense.

**Comment by adambraimbridge** [comment]
^ This is awesome. Thanks!

**Comment by simonplend** [comment]
@adambraimbridge It was a great question and got me thinking about about a bunch of stuff I hadn't considered before :star2:

**Comment by taktran** [comment]
Great discussion 👍 

I might do this for [ebi](https://github.com/Financial-Times/ebi) too :)

**Comment by taktran** [comment]
Would this also mean you need to turn off renovate PRs for upgrading node versions?

eg, https://github.com/Financial-Times/github/pull/21

**Comment by simonplend** [comment]
@taktran Hmm, yeah, I think so :confused:

**Comment by simonplend** [comment]
@taktran Update: no, as we've found with the `github` CLI tool, we haven't had to turn off Renovate upgrading node versions as you can specify just the major versions in CircleCI configuration and `.nvmrc`, and in the `engines.node` field in `package.json` you can use `^` rather than pinning. Renovate will only open pull requests for updates when it sees a version of node that no longer has LTS support, based on [how we have it configured](https://github.com/Financial-Times/renovate-config-next/blob/604540e5c587d24feadefcec702f4dd87e69eb10/renovate.json#L25) ([Renovate `supportPolicy` documentation](https://renovatebot.com/docs/node/#configuring-support-policy)).
